// src/lib/components/Qualification.svelte
<script lang="ts">
	interface QualificationItem {
		title: string;
		subtitle: string;
		date: string;
		position: 'left' | 'right';
	}

	interface QualificationData {
		work: QualificationItem[];
		education: QualificationItem[];
	}

	type TabType = 'work' | 'education';

	let data: QualificationData | null = $state(null);
	let loading = $state(true);
	let error = $state(false);
	let activeTab: TabType = $state('work');

	async function fetchData() {
		try {
			const res = await fetch('/assets/data/qualification.json');
			if (!res.ok) throw new Error();
			data = await res.json();
		} catch {
			error = true;
		} finally {
			loading = false;
		}
	}

	$effect(() => { fetchData(); });
</script>

<section class="qualification section" id="qualification">
	{#if loading}
		<div class="container loading">Loading qualifications</div>
	{:else if error}
		<div class="container">Error loading qualification information.</div>
	{:else if data}
		<h2 class="section__title">Qualification</h2>

		<div class="qualification__container container">
			<div class="qualification__tabs">
				<div
					class="qualification__button button--flex"
					class:qualification__active={activeTab === 'work'}
					onclick={() => activeTab = 'work'}
					onkeypress={() => activeTab = 'work'}
					role="button"
					tabindex="0"
				>
					<i class="uil uil-briefcase-alt qualification__icon"></i>
					Work experience
				</div>
				<div
					class="qualification__button button--flex"
					class:qualification__active={activeTab === 'education'}
					onclick={() => activeTab = 'education'}
					onkeypress={() => activeTab = 'education'}
					role="button"
					tabindex="0"
				>
					<i class="uil uil-graduation-cap qualification__icon"></i>
					Education
				</div>
			</div>

			<div class="qualification__sections">
				<div class="qualification__content" class:qualification__active={activeTab === 'work'} data-content>
					{#each data.work as item, index}
						{@const isLast = index === data.work.length - 1}
						{#if item.position === 'left'}
							<div class="qualification__data qualification__left">
								<div>
									<h3 class="qualification__title">{item.title}</h3>
									<span class="qualification__subtitle">{item.subtitle}</span>
									<div class="qualification__calendar">
										<i class="uil uil-calendar-alt"></i>
										{item.date}
									</div>
								</div>
								<div>
									<span class="qualification__rounder"></span>
									{#if !isLast}<span class="qualification__line"></span>{/if}
								</div>
							</div>
						{:else}
							<div class="qualification__data qualification__right">
								<div></div>
								<div>
									<span class="qualification__rounder"></span>
									{#if !isLast}<span class="qualification__line"></span>{/if}
								</div>
								<div>
									<h3 class="qualification__title">{item.title}</h3>
									<span class="qualification__subtitle">{item.subtitle}</span>
									<div class="qualification__calendar">
										<i class="uil uil-calendar-alt"></i>
										{item.date}
									</div>
								</div>
							</div>
						{/if}
					{/each}
				</div>

				<div class="qualification__content" class:qualification__active={activeTab === 'education'} data-content>
					{#each data.education as item, index}
						{@const isLast = index === data.education.length - 1}
						{#if item.position === 'left'}
							<div class="qualification__data qualification__left">
								<div>
									<h3 class="qualification__title">{item.title}</h3>
									<span class="qualification__subtitle">{item.subtitle}</span>
									<div class="qualification__calendar">
										<i class="uil uil-calendar-alt"></i>
										{item.date}
									</div>
								</div>
								<div>
									<span class="qualification__rounder"></span>
									{#if !isLast}<span class="qualification__line"></span>{/if}
								</div>
							</div>
						{:else}
							<div class="qualification__data qualification__right">
								<div></div>
								<div>
									<span class="qualification__rounder"></span>
									{#if !isLast}<span class="qualification__line"></span>{/if}
								</div>
								<div>
									<h3 class="qualification__title">{item.title}</h3>
									<span class="qualification__subtitle">{item.subtitle}</span>
									<div class="qualification__calendar">
										<i class="uil uil-calendar-alt"></i>
										{item.date}
									</div>
								</div>
							</div>
						{/if}
					{/each}
				</div>
			</div>
		</div>
	{/if}
</section>

// src/components/Qualification/Qualification.tsx
import React, { useState } from 'react'
import { useJsonData } from '../../hooks/useJsonData'
import { QualificationData, QualificationItem } from '../../types'

type TabType = 'work' | 'education';

const Qualification: React.FC = () => {
  const { data: qualifications, loading, error } = useJsonData<QualificationData>('/assets/data/qualification.json');
  const [activeTab, setActiveTab] = useState<TabType>('work');

  const renderQualificationItem = (item: QualificationItem, index: number, array: QualificationItem[]) => {
    const isLast = index === array.length - 1;

    if (item.position === 'left') {
      return (
        <div key={index} className={`qualification__data qualification__${item.position}`}>
          <div>
            <h3 className="qualification__title">{item.title}</h3>
            <span className="qualification__subtitle">{item.subtitle}</span>
            <div className="qualification__calendar">
              <i className="uil uil-calendar-alt"></i>
              {item.date}
            </div>
          </div>
          <div>
            <span className="qualification__rounder"></span>
            {!isLast && <span className="qualification__line"></span>}
          </div>
        </div>
      );
    } else {
      return (
        <div key={index} className={`qualification__data qualification__${item.position}`}>
          <div></div>
          <div>
            <span className="qualification__rounder"></span>
            {!isLast && <span className="qualification__line"></span>}
          </div>
          <div>
            <h3 className="qualification__title">{item.title}</h3>
            <span className="qualification__subtitle">{item.subtitle}</span>
            <div className="qualification__calendar">
              <i className="uil uil-calendar-alt"></i>
              {item.date}
            </div>
          </div>
        </div>
      );
    }
  };

  if (loading) {
    return (
      <section className="qualification section" id="qualification">
        <div className="container">Loading qualifications...</div>
      </section>
    );
  }

  if (error) {
    console.error('Error loading qualification data:', error);
    return (
      <section className="qualification section" id="qualification">
        <div className="container">Error loading qualification information.</div>
      </section>
    );
  }

  return (
    <section className="qualification section" id="qualification">
      <h2 className="section__title">Qualification</h2>

      <div className="qualification__container container">
        <div className="qualification__tabs">
          <div
            className={`qualification__button button--flex ${activeTab === 'work' ? 'qualification__active' : ''}`}
            onClick={() => setActiveTab('work')}
          >
            <i className="uil uil-briefcase-alt qualification__icon"></i>
            Work experience
          </div>
          <div
            className={`qualification__button button--flex ${activeTab === 'education' ? 'qualification__active' : ''}`}
            onClick={() => setActiveTab('education')}
          >
            <i className="uil uil-graduation-cap qualification__icon"></i>
            Education
          </div>
        </div>

        <div className="qualification__sections">
          {/* ==================== WORK EXPERIENCE ==================== */}
          <div className={`qualification__content ${activeTab === 'work' ? 'qualification__active' : ''}`} data-content>
            {qualifications?.work?.map((work, index) =>
              renderQualificationItem(work, index, qualifications.work)
            )}
          </div>

          {/* ==================== EDUCATION ==================== */}
          <div className={`qualification__content ${activeTab === 'education' ? 'qualification__active' : ''}`} data-content>
            {qualifications?.education?.map((edu, index) =>
              renderQualificationItem(edu, index, qualifications.education)
            )}
          </div>
        </div>
      </div>
    </section>
  )
}

export default Qualification
