// src/lib/components/About.svelte
<script lang="ts">
	interface AboutData {
		title: string;
		subtitle: string;
		description: string;
		resume: string;
	}

	let { data }: { data: AboutData } = $props();
</script>

<section class="about section" id="about">
	<h2 class="section__title">{data.title}</h2>

	<div class="about__container container grid">
		<div class="about__data">
			<p class="about__description">{data.description}</p>

			<div class="about__buttons" style="display: flex; justify-content: center; width: 100%">
				{#if data.resume}
					<a
						href={data.resume}
						class="button button--flex"
						target="_blank"
						rel="noopener noreferrer"
					>
						See Full Resume<i class="uil uil-cloud-download button__icon"></i>
					</a>
				{/if}
			</div>
		</div>
	</div>
</section>

// src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';
import { AboutService } from './about.service';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {
  aboutData: any;

  constructor(private aboutService: AboutService) {}

  ngOnInit(): void {
    this.aboutService.getAboutData().subscribe(data => {
      this.aboutData = data;
      console.log('About Data:', data); // Log the JSON data here
      console.log('AboutData:', this.aboutData); // Log the JSON data here
    });
  }
}

<section class="about section" id="about">
    <h2 class="section__title">{{ aboutData?.title }}</h2>
    <span class="section__subtitle">{{ aboutData?.subtitle }}</span>

    <div class="about__container container grid">
        <!--img src="/assets/img/about.jpg" alt="" class="about__img"-->
        <div class="about__data">
            <p class="about__description">{{ aboutData?.description }}</p>

            <!--div class="about__info">
                <div>
                    <span class="about__info-title">04+</span>
                    <span class="about__info-name">Years <br> experience</span>
                </div>
                <div>
                    <span class="about__info-title">20+</span>
                    <span class="about__info-name">Completed <br> projects</span>
                </div>
                <div>
                    <span class="about__info-title">04+</span>
                    <span class="about__info-name">Companies <br> worked</span>
                </div>
            </div-->

            <div class="about__buttons">
                <a *ngIf="aboutData?.resume" [href]="aboutData.resume" class="button button--flex" target="_blank"
                    rel="noopener noreferrer">
                    See Full Resume<i class="uil uil-cloud-download button__icon"></i>
                </a>
            </div>
        </div>
    </div>
</section>
