// src/lib/components/Qualification.svelte
<script lang="ts">
	interface QualificationItem {
		title: string;
		subtitle: string;
		date: string;
		position: 'left' | 'right';
	}

	interface QualificationData {
		work: QualificationItem[];
		education: QualificationItem[];
	}

	type TabType = 'work' | 'education';

	let { data }: { data: QualificationData } = $props();
	let activeTab: TabType = $state('work');
</script>

<section class="qualification section" id="qualification">
	<h2 class="section__title">Qualification</h2>

	<div class="qualification__container container">
		<div class="qualification__tabs">
			<div
				class="qualification__button button--flex"
				class:qualification__active={activeTab === 'work'}
				onclick={() => activeTab = 'work'}
				onkeypress={() => activeTab = 'work'}
				role="button"
				tabindex="0"
			>
				<i class="uil uil-briefcase-alt qualification__icon"></i>
				Work experience
			</div>
			<div
				class="qualification__button button--flex"
				class:qualification__active={activeTab === 'education'}
				onclick={() => activeTab = 'education'}
				onkeypress={() => activeTab = 'education'}
				role="button"
				tabindex="0"
			>
				<i class="uil uil-graduation-cap qualification__icon"></i>
				Education
			</div>
		</div>

		<div class="qualification__sections">
			<div class="qualification__content" class:qualification__active={activeTab === 'work'} data-content>
				{#each data.work as item, index}
					{@const isLast = index === data.work.length - 1}
					{#if item.position === 'left'}
						<div class="qualification__data qualification__left">
							<div>
								<h3 class="qualification__title">{item.title}</h3>
								<span class="qualification__subtitle">{item.subtitle}</span>
								<div class="qualification__calendar">
									<i class="uil uil-calendar-alt"></i>
									{item.date}
								</div>
							</div>
							<div>
								<span class="qualification__rounder"></span>
								{#if !isLast}<span class="qualification__line"></span>{/if}
							</div>
						</div>
					{:else}
						<div class="qualification__data qualification__right">
							<div></div>
							<div>
								<span class="qualification__rounder"></span>
								{#if !isLast}<span class="qualification__line"></span>{/if}
							</div>
							<div>
								<h3 class="qualification__title">{item.title}</h3>
								<span class="qualification__subtitle">{item.subtitle}</span>
								<div class="qualification__calendar">
									<i class="uil uil-calendar-alt"></i>
									{item.date}
								</div>
							</div>
						</div>
					{/if}
				{/each}
			</div>

			<div class="qualification__content" class:qualification__active={activeTab === 'education'} data-content>
				{#each data.education as item, index}
					{@const isLast = index === data.education.length - 1}
					{#if item.position === 'left'}
						<div class="qualification__data qualification__left">
							<div>
								<h3 class="qualification__title">{item.title}</h3>
								<span class="qualification__subtitle">{item.subtitle}</span>
								<div class="qualification__calendar">
									<i class="uil uil-calendar-alt"></i>
									{item.date}
								</div>
							</div>
							<div>
								<span class="qualification__rounder"></span>
								{#if !isLast}<span class="qualification__line"></span>{/if}
							</div>
						</div>
					{:else}
						<div class="qualification__data qualification__right">
							<div></div>
							<div>
								<span class="qualification__rounder"></span>
								{#if !isLast}<span class="qualification__line"></span>{/if}
							</div>
							<div>
								<h3 class="qualification__title">{item.title}</h3>
								<span class="qualification__subtitle">{item.subtitle}</span>
								<div class="qualification__calendar">
									<i class="uil uil-calendar-alt"></i>
									{item.date}
								</div>
							</div>
						</div>
					{/if}
				{/each}
			</div>
		</div>
	</div>
</section>

// src/app/qualification/qualification.component.ts
import { Component, OnInit } from '@angular/core';
import { QualificationService } from './qualification.service';

@Component({
  selector: 'app-qualification',
  templateUrl: './qualification.component.html',
  styleUrls: ['./qualification.component.css']
})
export class QualificationComponent implements OnInit {
  qualifications: any = {};

  constructor(private qualificationService: QualificationService) {}

  ngOnInit(): void {
    this.qualificationService.getQualifications().subscribe(data => {
      this.qualifications = data;
    });
  }
}
<section class="qualification section"  id="qualification">
    <h2 class="section__title">Qualification</h2>
    <span class="section__subtitle">My personal journey</span>

    <div class="qualification__container container">
        <div class="qualification__tabs">
            <div class="qualification__button button--flex qualification__active" data-target='#work'>
                <i class="uil uil-briefcase-alt qualification__icon"></i>
                Work experience
            </div>
            <div class="qualification__button button--flex" data-target='#education'>
                <i class="uil uil-graduation-cap qualification__icon"></i>
                Education
            </div>
        </div>

        <div class="qualification__sections">
            <!--==================== WORK EXPERIENCE ====================-->
            <div class="qualification__content  qualification__active" data-content id="work">
                <div *ngFor="let work of qualifications.work" class="qualification__data qualification__{{ work.position }}">
                    <!-- For left-aligned content -->
                    <ng-container *ngIf="work.position === 'left'">
                      <div>
                        <h3 class="qualification__title">{{ work.title }}</h3>
                        <span class="qualification__subtitle">{{ work.subtitle }}</span>
                        <div class="qualification__calendar">
                          <i class="uil uil-calendar-alt"></i>
                          {{ work.date }}
                        </div>
                      </div>
                      <div>
                        <span class="qualification__rounder"></span>
                        <span
                          class="qualification__line"
                          *ngIf="work !== qualifications.work[qualifications.work.length - 1]"
                        ></span>
                      </div>
                    </ng-container>
                  
                    <!-- For right-aligned content -->
                    <ng-container *ngIf="work.position === 'right'">
                      <div></div>
                      <div>
                        <span class="qualification__rounder"></span>
                        <span
                          class="qualification__line"
                          *ngIf="work !== qualifications.work[qualifications.work.length - 1]"
                        ></span>
                      </div>
                      <div>
                        <h3 class="qualification__title">{{ work.title }}</h3>
                        <span class="qualification__subtitle">{{ work.subtitle }}</span>
                        <div class="qualification__calendar">
                          <i class="uil uil-calendar-alt"></i>
                          {{ work.date }}
                        </div>
                      </div>
                    </ng-container>
                  </div>
            </div>
            <!--==================== EDUCATION ====================-->
            <div class="qualification__content" data-content id="education">
                <div class="qualification__data  qualification__left">
                    <div>
                        <h3 class="qualification__title">Computer Engineering</h3>
                        <span class="qualification__subtitle">Universidad San Ignacio de Loyola</span>
                        <div class="qualification__calendar">
                            <i class="uil uil-calendar-alt"></i>
                            2015 - 2020
                        </div>
                    </div>
                    <div>
                        <span class="qualification__rounder"></span>
                        <span class="qualification__line"></span>
                    </div>
                </div>
                <div class="qualification__data  qualification__right">
                    <div></div>
                    <div>
                        <span class="qualification__rounder"></span>
                        <!--span class="qualification__line"></span-->
                    </div>
                    <div>
                        <h3 class="qualification__title">International Business</h3>
                        <span class="qualification__subtitle">San Ignacio University</span>
                        <div class="qualification__calendar">
                            <i class="uil uil-calendar-alt"></i>
                            2015 - 2021
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
